AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'bin/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 155

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
